migrations/src/2_system.ts
package.json
test-utils/constants.ts
truffle-config.js

Adds support to deploy to Kovan

Add Kovan deployment

---

contracts/interfaces/IBoostDirector.sol
contracts/savings/BoostDirector.sol
contracts/z_mocks/savings/MockBoostedSavingsVault.sol
package.json
test/savings/savings-vault.spec.ts
yarn.lock

Feeder pools boost

---

contracts/feeders/peripheral/FeederWrapper.sol
contracts/savings/peripheral/SaveWrapper.sol
tasks.config.ts
tasks/BoostedSavingsVault.ts
tasks/FeederWrapper.ts
tasks/SaveWrapper.ts

- Add `saveViaSwap` function to SaveWrapper
- Use `safeTransferFrom` function
- Add tasks for FeederWrapper
**TODO**

Improve Feeder/Save wrappers

---

contracts/interfaces/IEjector.sol
contracts/interfaces/ISavingsManager.sol
package.json
tasks.config.ts
tasks/ops.ts
yarn.lock

Operations tasks using OZ Defender Relay

---

.github/workflows/coverage.yaml
.github/workflows/lint-sol.yaml
.github/workflows/lint-ts.yaml
.github/workflows/test.yaml
contracts/masset/versions/MusdEth.json
contracts/peripheral/Curve/ICurve.sol
contracts/savings/SavingsManager.sol
package.json
tasks/deployPolygon.ts
tasks/feeder.ts
tasks/mBTC.ts
tasks/mUSD.ts
tasks/utils/rates-utils.ts
tasks/utils/snap-utils.ts
tasks/utils/storage-utils.ts
tasks/utils/tokens.ts
tsconfig.json
yarn.lock

Polygon tasks

---

contracts/masset/peripheral/CompoundInegration.sol
contracts/masset/peripheral/ICompound.sol
contracts/polygon/IAaveIncentivesController.sol
contracts/z_mocks/masset/MockCompound.sol
contracts/z_mocks/shared/MockAaveIncentivesController.sol
tasks-fork.config.ts
tasks.config.ts
tasks/deployAaveIntegration.ts
tasks/deployPolygon.ts
tasks/feeder.ts
tasks/mBTC.ts
tasks/mUSD.ts
tasks/ops.ts
tasks/utils/defender-utils.ts
tasks/utils/deploy-utils.ts
tasks/utils/snap-utils.ts
tasks/utils/storage-utils.ts
test-fork/feeders/feeders-musd-cream.spec.ts
test-fork/mUSD/aave2-migration.spec.ts
test-utils/machines/standardAccounts.ts
test/masset/peripheral/compound.sepc.ts
test/masset/peripheral/compound.spec.ts

Compound/Cream Integration

---

contracts/masset/versions/BasketManager.json
contracts/masset/versions/MusdLegacy.json
tasks/feeder.ts
tasks/mBTC.ts
tasks/mUSD.ts
tasks/ops.ts
tasks/utils/networkAddressFactory.ts
tasks/utils/rates-utils.ts
tasks/utils/snap-utils.ts
tasks/utils/storage-utils.ts
test-utils/machines/feederMachine.ts
test-utils/machines/mAssetMachine.ts
test/masset/admin.spec.ts

Hardhat task fixes to get protocol revenue and expenses

---

contracts/governance/staking/GamifiedToken.sol
contracts/governance/staking/StakedToken.sol
contracts/governance/staking/StakedTokenBPT.sol
contracts/governance/staking/StakedTokenMTA.sol
contracts/legacy/v-BUSD.sol
contracts/legacy/v-GUSD.sol
contracts/legacy/v-HBTC.sol
contracts/legacy/v-TBTC.sol
contracts/legacy/v-alUSD.sol
contracts/legacy/v-mBTC.sol
contracts/legacy/v-mUSD.sol
contracts/legacy/v-mUSD_original.sol
contracts/z_mocks/governance/MockStakedTokenWithPrice.sol
hardhat.config.ts
package.json
tasks-fork.config.ts
tasks.config.ts
tasks/deployLegacy.ts
tasks/deployRewards.ts
tasks/utils/etherscan.ts
tasks/utils/networkAddressFactory.ts
tasks/utils/tokens.ts
test/governance/staked-token-bpt.spec.ts
test/governance/staked-token-mta.spec.ts
test/governance/staked-token.spec.ts
types/stakedToken.ts
yarn.lock

Vault upgrades

---

contracts/legacy/v-mBTC.sol
contracts/legacy/v-mUSD.sol
hardhat.config.ts
tasks/deployLegacy.ts
tasks/deployRewards.ts
tasks/utils/deploy-utils.ts
tasks/utils/etherscan.ts
tasks/utils/networkAddressFactory.ts

Vault deployment

---

contracts/governance/staking/QuestManager.sol
contracts/governance/staking/StakedToken.sol
hardhat.config.ts
tasks-fork.config.ts
tasks.config.ts
tasks/deployRewards.ts
tasks/utils/networkAddressFactory.ts
test/governance/staking/staked-token-bpt.spec.ts
test/governance/staking/staked-token.spec.ts
types/stakedToken.ts

Staking token tests

---

contracts/emissions/ChildEmissionsController.sol
contracts/emissions/EmissionsController.sol
contracts/emissions/PolygonChildRecipient.sol
contracts/emissions/PolygonRootRecipient.sol
contracts/interfaces/IRootChainManager.sol
contracts/z_mocks/rewards/MockRewardsDistributionRecipient.sol
contracts/z_mocks/rewards/MockRootChainManager.sol
contracts/z_mocks/savings/MockStakingContract.sol
test-utils/time.ts
test/emissions/emission-controller-polygon.spec.ts
test/emissions/emission-controller.spec.ts

* Store dial weighted votes for each weekly epoch
* Merged polynomial emissions schedule

Dial weighted votes per epoch and polynomial emissions schedule

---

contracts/emissions/BasicRewardsForwarder.sol
contracts/emissions/BridgeForwarder.sol
contracts/emissions/EmissionsController.sol
contracts/emissions/L2BridgeRecipient.sol
contracts/emissions/L2EmissionsController.sol
contracts/interfaces/IVotes.sol
tasks/utils/rewardsUtils.ts
test/emissions/emission-controller-polygon.spec.ts
test/emissions/emission-controller.spec.ts

- Renamed files to distinguish specifically which chains they will be deployed on (prefix of "L2")
- Added comprehensive natspec comments and standardised spacing/layout
- Standardised naming convention of immutables to be "SNAKE_CASE" as per solidity docs
- Swept through to ensure events are being emitted everywhere

chore: Add comprehensive natspec comments and standardise naming

---

contracts/emissions/BridgeForwarder.sol
contracts/emissions/EmissionsController.sol
tasks/utils/deploy-utils.ts
tasks/utils/emissions-utils.ts
tasks/utils/networkAddressFactory.ts
tasks/utils/rewardsUtils.ts
test-fork/buy-and-make/recipient-upgrade.spec.ts
test-fork/emissions/emissions-mainnet-deployment.spec.ts
test-utils/time.ts
test/emissions/emission-controller-polygon.spec.ts

* `BridgeForwarder` needs to approve the bridge contract that locks bridged tokens
* EmissionsController fork tests

Emissions fork tests

---

tasks/deployIntegration.ts
tasks/deployRevenueForwarder.ts
tasks/poker.ts
tasks/utils/feederUtils.ts
tasks/utils/rewardsUtils.ts
test/governance/staking/staked-token-bpt.spec.ts
test/governance/staking/staked-token-mta.spec.ts
test/governance/staking/staked-token.spec.ts

fix eslint warnings on ts files

style(*): fix eslint warnings on ts files

---

tasks/feeder.ts

New task is to test against a forked chain. For example
```
export IMPERSONATE=Governor  
yarn task:fork feeder-migrate-bassets --fasset RAI
```

Added feeder-migrate-bassets task

---

test/emissions/emission-controller.spec.ts

Add tests to EmissionsController to cover multiple scenarios for getDialVoteHistory

test:adds tests for EmissionsController.getDialVoteHistory

---

tasks/utils/feederUtils.ts
tasks/utils/tokens.ts

todo: deploy PAave Integration + add verifyEtherscan

chore: FEI Feeder Pool deploy

---

contracts/emissions/VotiumBribeForwarder.sol
contracts/interfaces/IVotiumBribe.sol
tasks/deployEmissionsController.ts
tasks/utils/emissions-utils.ts

Adds VotiumBribeForwarder dial

feat: adds VotiumBribeForwarder

---

contracts/emissions/EmissionsController.sol
contracts/emissions/VotiumBribeForwarder.sol
contracts/z_mocks/emissions/MockDisperse.sol
contracts/z_mocks/emissions/MockVotiumBribe.sol
tasks/feeder.ts
test/buy-and-make/revenue-buy-back.spec.ts
test/buy-and-make/revenue-forwarder.spec.ts
test/emissions/disperse-forwarder.spec.ts
test/emissions/votium-bribe-forwarder.spec.ts
test/governance/staking/staked-token.spec.ts

- adds tests to VotiumBribeForwarder
- adds tests to  DisperseForwarder

test: adds tests to VotiumBribeForwarder

---

package.json
tasks/emissions.ts
tasks/utils/deploy-utils.ts
tasks/utils/emission-disperse-bal.ts
yarn.lock

1. it gets the report from the repo https://github.com/balancer-labs/bal-mining-scripts/blob/master/report
2. scale the values to match with the MTA disperse forwarder  balance
3. disperse the tokens to the recipients 
4. adds debug package to the project

build:adds subtask emission-disperse-bal

---

contracts/masset/peripheral/DudIntegration.sol
contracts/masset/peripheral/DudPlatform.sol
contracts/masset/peripheral/IDudPlatform.sol
test-fork/feeders/feeders-dudintegration.spec.ts
test/feeders/admin.spec.ts

Dud integration

---

tasks/stakingV2.ts

* Fixed Hardhat staked tasks against `mBPT` which were resolving to the wrong contract address.
* added more info and better formatting of `staked-snap` Hardhat task.
* added `staked-time` Hardhat task.

Staked Hardhat tasks

---

README.md
package.json
tasks/feeder.ts
tasks/mBTC.ts
tasks/mUSD.ts
tasks/ops.ts
tasks/poker.ts
tasks/rewards.ts
tasks/utils/flashbots.ts
tasks/utils/snap-utils.ts
tasks/vault.ts

* Added `compile-ts` to `prepublishOnly ` script so types are included in the published `@mstable/protocol` package.
* Change time in hh tasks from UTC to local times.
* Added new Feeder Pools to `over-boost` task.
* Updated README as some things were out of date

Fix prepublishOnly script

---

.solcover.js

- chore: ignores test coverage on Unliquidator.sol

chore: ignores test coverage on Unliquidator.sol

---

contracts/legacy-upgraded/imusd-mainnet-21.sol
tasks/utils/networkAddressFactory.ts

- updates Unwrapper mainnet address after deploying

chore: updates Unwrapper mainnet address

---

contracts/savings/peripheral/SaveWrapper.sol
contracts/z_mocks/savings/MockSavingsContract.sol
tasks/utils/networkAddressFactory.ts

feat: adds referrer field to SaveWrapper deposits methods

feat: adds referrer to SaveWrapper deposits

---

tasks/dials.ts

* Removed vault ids from `dials-snap` Hardhat task

Removed vault ids from dials-snap hh task

---

contracts/interfaces/ISavingsContract.sol
contracts/legacy-upgraded/imbtc-mainnet-22.sol
contracts/legacy-upgraded/imusd-mainnet-22.sol
contracts/legacy-upgraded/imusd-polygon-22.sol
contracts/rewards/boosted-staking/BoostedDualVault.sol
contracts/rewards/boosted-staking/BoostedVault.sol
contracts/rewards/staking/StakingRewards.sol
contracts/rewards/staking/StakingRewardsWithPlatformToken.sol
contracts/savings/SavingsContract.sol
contracts/savings/peripheral/SaveWrapper.sol
contracts/savings/peripheral/Unwrapper.sol

- feat: adds ISavingsContractV4

feat: adds ISavingsContractV4

---

tasks/emissions.ts
tasks/utils/emissions-split-buy-back.ts
test-utils/peripheral/uniswap.ts

Add new hardhat task `revenue-split-buy-back`

feat: adds task revenue-split-buy-back

---

.github/ISSUE_TEMPLATE/deployment_task.md

Issue https://github.com/mstable/mStable-contracts-V2/issues/46
Useful deployment check list

Create deployment template

---

contracts/buy-and-make/RevenueSplitBuyBack.sol
package.json
tasks/dials.ts
tasks/utils/networkAddressFactory.ts

* Added new Idle Finance contract to `dials-snap` Hardhat task
* Bumped package version to match the latest release

Idle finance

---

tasks/dials.ts
tasks/rewards.ts
test-fork/emissions/emissions-mainnet-deployment.spec.ts

* Output mUSD and mBTC revenue in hardhat task `collect-interest-dist`
* Update heading in `dials-snap` hardhat task output
* New `dials-dust-votes` hardhat task

Output mUSD and mBTC revenue in hh task collect-interest-dist

---

tasks/dials.ts

added check to remove looping over disabled dials. Disabled dials will not produce a console output anymore.

fix: remove disabled dials from output

---

tasks/emissions.ts
tasks/utils/emissions-split-buy-back.ts
test-utils/peripheral/uniswap.ts

- Updates slippage configuration on task revenue buy back 
- Adds utility function to get the best uniswap fee route
Closes https://github.com/mstable/mstable-v1-backlog/issues/61

refactor: revenue buy back slippage config

---

contracts/emissions/EmissionsController.sol
contracts/z_mocks/savings/MockSavingsContract.sol
tasks/deployEmissionsController.ts
tasks/utils/emissions-utils.ts
test-fork/emissions/emissions-mainnet-upgrade.spec.ts
test/buy-and-make/revenue-buy-back.spec.ts
test/buy-and-make/revenue-split-buy-back.spec.ts
test/emissions/emission-controller-polygon.spec.ts
test/emissions/emission-controller.spec.ts
test/savings/savings-manager.spec.ts

Related to https://github.com/mstable/mStable-contracts/issues/374
- Changes topLineEmissions to  match definition at https://forum.mstable.org/t/mccp-24-reduce-weekly-mta-emissions/912
- Fixes number of epochs based on the discussion here https://github.com/mstable/mStable-contracts/issues/374#issuecomment-1216487243
- Updates test
- Adds fork test to validate the upgrade
- Updates hardhat task

refact: updates  emissions controller to a linear function

---

tasks/masset.ts
tasks/utils/etherscan.ts

* added `masset-swap` Hardhat task
* `verifyEtherscan` to ignore `local` network

Hardhat tasks

---

tasks/emissions.ts
tasks/utils/emissions-split-buy-back.ts

- fix: buyback calculations when balance is low

fix: buyback calculations when balance is low
