mstable/mStable-contracts

- contracts/integrations/AbstractBuyAndMint.sol
- contracts/integrations/IMintWith1Inch.sol
- contracts/integrations/MintWith1Inch.sol
- contracts/z_mocks/integrations/IBuyAndMint.sol
- contracts/z_mocks/integrations/MintWithKyber.sol
- test/integrations/AbstractBuyAndMint.behaviour.ts
- test/integrations/TestMintWith1inch.spec.ts
- test/integrations/TestMintWithKyber.spec.ts.parked
imple DEX integration to 1inch (a.k.a OneSplit) to enable ETH -> bAsset purchases. Use the output bAsset to mint mAsset.
> Mint with ETH using 1inch

- contracts/masset/forge-validator/ForgeValidator.sol
- test/masset/TestMassetRedemption.spec.ts
- test/masset/forge-validator/TestForgeValidatorR.spec.ts
Remove the concept of a bAsset being "breached". This was when it was within 1% of its max weight and applies unnecessary constraints onto redemption.
If a bAsset is close to its max weight, then redeeming any other bAsset would naturally push it overweight.
> ForgeValidator 1.1

- package.json
- yarn.lock
@alsco77 Oh sorry..wanted to double-check this in CI here but it looks like it's not enabled for forks. 
Please feel free to close this.
#89 Ran clean for me locally with this update. 
The reporter may still slow things down a little - there's a boolean `enabled` option for the buidler config you can set conditionally with an env variable if you'd rather not run this all the time.
> Upgrade buidler-gas-reporter to 0.1.4-beta.4

- .circleci/config.yml
- contracts/masset/Masset.sol
- test/masset/TestMasset.spec.ts
- test/masset/TestMassetRedeemMulti.spec.ts
**Upgrade type**: Proxy contract upgrade
**Affected file**: `Masset.sol`
**Proxy address**: `0xe2f2a5C287993345a840Db3B0845fbC70f5935a5`
**New version**: 1.1
Adds a redemption fee property for use in `redeemMasset`
- New storage prop: `redemptionFee` :rotating_light:
- New function: `setRedemptionFee` - Allow fee to be updated by governance
- Changed function signature: Update signature and existing calls to `_settleRedemption`. Now accepts uint instead of bool
Deployed address: `0xe4c5b1765bf420016027177289908c5a3ea7668e`
ProposeUpgrade tx: 14:13 CET 08/02
AcceptUpgrade tx: 
Deployed address: `0x121a86dd617c0584cf1bdffc92e36d9100000ca7`
ProposeUpgrade tx: 12:13 CET 07/02
AcceptUpgrade tx:  14:07 CET 07/02
> Redemption fee

- buidler.config.ts
- contracts/masset/platform-integrations/CompoundIntegration.sol
- contracts/z_mocks/masset/platform-integrations/MockAave.sol
- contracts/z_mocks/masset/platform-integrations/MockCToken.sol
- contracts/z_mocks/masset/platform-integrations/MockCompoundIntegration.sol
- scripts/src/utils/mUSDMinter.ts
- test-utils/constants.ts
- test/masset/TestMasset.spec.ts
- test/masset/TestMassetRedemption.spec.ts
- test/masset/platform-integrations/TestAaveIntegration.spec.ts
- test/masset/platform-integrations/TestCompoundIntegration.spec.ts
**Upgrade type**: PROXY CONTRACT UPGRADE
**Affected file**: `CompoundIntegration.sol`
**Proxy address**: `0xd55684f4369040c12262949ff78299f2bc9db735`
**New version**: 1.1
Upgrades the Compound Integration, addressing some UX problems.
- New function `collectRewardToken` allows the mStable Governor to collect the `$COMP` airdrops
- Withdrawing minute amounts of `underlying` causes `withdraw` to fail if the cToken and Underlying have different decimals. There is now logic to ensure that if `cTokensToRedeem == 0`, then just skip the redemption
- `checkBalance` now just calculates using the exchangeRate, instead of spending 80,000 gas to check the balanceOfUnderlying. This massively reduces gas costs for deposits into the Savings Contract
Deployed address: …
> Compound Integration upgrade

- .circleci/config.yml
- contracts/savings/SavingsManager.sol
- test-utils/assertions.ts
- test/savings/TestSavingsManager.spec.ts
**Upgrade type**: MODULE REPLACEMENT VIA NEXUS
**Affected file**: `SavingsManager.sol`
**Version**: 1.1
Address bug originally submitted through Bug Bounty - See [Devan - Bug bounty response.pdf](https://github.com/mstable/mStable-contracts/files/5048099/Devan.-.Bug.bounty.response.pdf)
Removes the blocker on collecting interest more than once in 30 minute period.
Retains existing 'extrapolatedAPY' calculations when it has been longer than 30 minutes since the last interest collection.
If it has been less than 30 minutes, it simply checks that the supply has not inflated by more than 0.1% (or 1e15) during that PERIOD (30 mins). At a 0.1% 'SWAP' fee, this would mean that the total supply of the mAsset would need to be swapped between the two collections, if this were to be hit. …
> Implemented period based yield analysis on SavingsManager

- README.md
I ran into issues using Node.js v13.10.1 and found that that the LTS v10.22.0 release works. I also found that the default block gas limit is too low for the setting in `truffle-config.js`.
> Added prerequisites and set block gas limit

- package.json
Dry run output:
```
npm notice
npm notice 📦  @mstable/protocol@1.1.2
npm notice === Tarball Contents ===
npm notice 35.5kB  LICENSE
npm notice 54.1kB  artifacts/AaveIntegration.json
npm notice 53.2kB  artifacts/AaveIntegrationV2.json
npm notice 53.7kB  artifacts/AaveIntegrationV3.json
npm notice 559B    artifacts/Address.json
npm notice 14.0kB  artifacts/AdminUpgradeabilityProxy.json
npm notice 11.7kB  artifacts/BaseAdminUpgradeabilityProxy.json
npm notice 1.3kB   artifacts/BaseUpgradeabilityProxy.json
npm notice 132.7kB artifacts/BasketManager.json
npm notice 16.7kB  artifacts/ClaimableGovernor.json
npm notice 565B    artifacts/CommonHelpers.json
npm notice 53.5kB  artifacts/CompoundIntegration.json
npm notice 275B    artifacts/Context.json
npm notice 21.2kB …
```
> Include artifacts in npm package

- README.md
It's not clear that the contract artifacts are meant to be used via the `@mstable/protocol` npm package. This PR adds an explicit note for this.
> docs: add note about contract artifacts in README

- contracts/masset/liquidator/ILiquidator.sol
- contracts/masset/liquidator/Liquidator.sol
- contracts/z_mocks/shared/MockCurveMetaPool.sol
- contracts/z_mocks/shared/MockTrigger.sol
- contracts/z_mocks/shared/MockUniswap.sol
- test/masset/liquidator/TestLiquidatorContract.spec.ts
The following changes have been made to ensure that a reasonable amount of USDC/mUSD is purchased when liquidating COMP:
- require sender to be non smart contract (i.e. enforce tx.origin == msg.sender)
- add a minimum amount of bAsset (USDC) to receive per sellToken (COMP)
- add a fix to Curve to ensure that the rate is always >= 0.95
Address: 0x35103a8fafa0c935b7a91e8356c8a05906c80210
1. [x] Deploy Liquidator
2. [x] Propose Liquidator upgrade
3. [x] Accept proposed upgrade
> Add minimum purchase amount on liquidations

- README.md
- contracts/z_mocks/shared/DeadToken.sol
- tasks.config.ts
- tasks/deployMbtc.ts
- tasks/mBTC.ts
- test-utils/btcConstants.ts
- test-utils/math.ts
- test/masset/swap.spec.ts
> post launch and mBTC snap task

- tasks/mBTC.ts
> Enhancements to mBTC snap reporting

- contracts/feeders/FeederPool.sol
- contracts/z_mocks/nexus/MockNexus.sol
- test-utils/machines/feederMachine.ts
- test-utils/machines/mAssetMachine.ts
- test-utils/machines/standardAccounts.ts
- test/feeders/admin.spec.ts
- test/feeders/basic-fns.spec.ts
- test/feeders/mint.spec.ts
- test/feeders/redeem.spec.ts
- test/feeders/swap.spec.ts
- test/masset/admin.spec.ts
- test/savings/savings-contract.spec.ts
- test/savings/savings-vault.spec.ts
> Feeder pool tests

- contracts/feeders/peripheral/FeederWrapper.sol
- tasks/deployFeeder.ts
- Add a basic FeederWrapper contract; Ownable but with no other storage or initialisation
- Add FeederWrapper deploy and approve step to `deployFeeder` task
> Add FeederWrapper

- .eslintrc.js
- contracts/savings/peripheral/SaveWrapper.sol
- package.json
- tasks.config.ts
- tasks/BoostedSavingsVault.ts
- tasks/SaveWrapper.ts
- tasks/deployAaveIntegration.ts
- tasks/deployMbtc.ts
- tasks/taskUtils.ts
- yarn.lock
- Make SaveWrapper stateless (that is, aside from being `Ownable`) so it can be flexible about assets supported
- Define pattern for discrete Hardhat tasks with params
- Disable some eslint rules
Tested on Ropsten, including a test sBTC/WETH pair on Uniswap.
> Flexible SaveWrapper

- contracts/shared/StableMath.sol
The result of "9e38 / 1e18" should be "9e20" instead of "9e18".
I guess, what the comment intends to explain is "9e36 / 1e18 = 9e18", based on the context.
> Correct the misleading comment

- tasks/mUSD.ts
- tasks/utils/snap-utils.ts
To run for the current block
```
yarn run task --network mainnet rewards
```
To run for a past block
```
yarn run task --network mainnet rewards --block 12680538
```
Example output
```
Getting platform tokens at block 12682476, Tue, 22 Jun 2021 06:40:23 GMT
COMP accrued
USDC                 38.79
Integration           0.00
Liquidator          494.76
Total               533.56     121,892.52 USDC (228 COMP/USDC)
stkAAVE accrued
sUSD                68.72
USDT               168.30
DAI                168.30
GUSD                22.90
BUSD                 0.00
WBTC                19.39
Liquidator           0.00 unlock Sun, 11 Jan 1970 00:00:00 GMT
Total              447.61      91,308.23 USDC (203 AAVE/USDC)
```
> Feature: added rewards task

- .prettierrc
- contracts/interfaces/IRewardsDistributionRecipient.sol
- contracts/rewards/RewardsDistributionRecipient.sol
- contracts/rewards/RewardsDistributor.sol
- contracts/rewards/staking/StakingRewardsWithPlatformToken.sol
- contracts/z_mocks/rewards/MockRewardsDistributionRecipient.sol
- package.json
- test/rewards/TestRewardsDistributor.spec.ts
- yarn.lock
- Adds `getPlatformToken()` to `StakingRewardsWithPlatformToken.sol`
- Adds argument of `platformAmounts` to `distributeRewards()` in `RewardsDistributor.sol`
- Updates `DistributedReward` event to include `platformAmounts` and `platformToken`
- Updates tests fo `RewardsDistributor.sol`
> Support transfers of platformToken in RewardsDistributor

- contracts/rewards/staking/StakingRewards.sol
- contracts/rewards/staking/StakingRewardsWithPlatformToken.sol
- package.json
- tasks/deployPolygon.ts
- tasks/utils/networkAddressFactory.ts
- test/rewards/staking-rewards-with-platform-token.spec.ts
- test/rewards/staking-rewards.spec.ts
> Set staking rewards duration on deployment

- contracts/masset/liquidator/Liquidator.sol
- package.json
- tasks/feeder.ts
- tasks/ops.ts
- tasks/utils/networkAddressFactory.ts
- tasks/utils/rates-utils.ts
- tasks/utils/snap-utils.ts
- test-fork/feeders/feeders-musd-alchemix.spec.ts
- test/masset/liquidator.spec.ts
- test/masset/peripheral/aavev2.spec.ts
- test/masset/peripheral/compound.spec.ts
- test/rewards/boosted-dual-vault.spec.ts
- test/rewards/boosted-vault.spec.ts
- test/savings/savings-manager.spec.ts
> Liquidator upgrade for ALCX

- README.md
- test/feeders/admin.spec.ts
- test/rewards/boosted-vault.spec.ts
Tests relying on timestamps are failing intermittently as the timestamp increase cadence is not necessarily deterministic.
Trying to fix them all here. May need to run the CI a couple dozen times to catch the failing tests
> wip: Fix intermittently failing CI

- .github/workflows/test-emissions.yaml
- contracts/emissions/EmissionsController.sol
- test/emissions/emission-controller-polygon.spec.ts
- test/emissions/emission-controller.spec.ts
Changes:
- Changes scale to 200 to support uint8
- Packs 16 preferences to an arr
- Set up dummy dialId of 0
- Loops through user prefs while dialId > 0
- Enforces all dialIds to be > 0
- Runs linter via husky
- Fix failing test cases
Design choice:
Assumption: dialId should correspond to position in array, and not be used as offset.
When packing the preferences to single arr, it makes sense to loop through until some breaking point (either 16 entries, or first dial being 0). IN order to do this, I introduced a dud dial at position 0, and then we loop through the preferences while id != 0.
We could however, when setting preferences, signal the final entry by setting dialId to be 256 on the end of the array. This would mean we don't need to worry about the empty entry (which it emits …
> feat: Packed preferences

- contracts/emissions/EmissionsController.sol
- test-utils/time.ts
- test/emissions/emission-controller-polygon.spec.ts
- test/emissions/emission-controller.spec.ts
**What**
- Intermediary step in distribution with only capped && non disabled. If over cap, takes cap% for them, and reduces from total votes and top level emission accordingly
- Generalised `cap` variable set at dial creation time
**Why**
- Previous impl assumes that the staking contracts always received >10% of the votes which may not be true
- Previous impl assumes staking contracts are the only ones with caps
- Previous impl did not factor in the reduction of stakingContract votes on overall vote count
**What**
- Removed while loop in favour of 2 step if statement
**Why**
- When looping through the historic rewards, the count we are looking for is either at:
- the end of array (requires reading + new entry) or
- at the second last entry (requires reading) or
- it doesn't exist, if the …
> Generalise cap function and improve readability

- contracts/buy-and-make/RevenueBuyBack.sol
- contracts/emissions/BasicRewardsForwarder.sol
- contracts/emissions/README.md
- contracts/z_mocks/masset/MockMasset.sol
- contracts/z_mocks/savings/MockStakingContract.sol
- test/buy-and-make/revenue-buy-back.spec.ts
`RevenueBuyBack` contract changes
* Added `BuyBackRewards` and `DonatedRewards` events
* Renamed `minBassetPercentage` to `minMasset2BassetPrice`
* Added approval of Uniswap to transfer bAssets from `RevenueBuyBack`
Other changes
* Minor README updates
* Added basic `RevenueBuyBack` unit tests
> RevenueBuyBack fixes and tests

- contracts/buy-and-make/RevenueBuyBack.sol
- contracts/emissions/BridgeForwarder.sol
- contracts/emissions/EmissionsController.sol
- contracts/emissions/L2BridgeRecipient.sol
- contracts/emissions/L2EmissionsController.sol
- contracts/interfaces/IEmissionsController.sol
- hardhat-fork-polygon.config.ts
- package.json
- tasks-fork-polygon.config.ts
- tasks-fork.config.ts
- tasks.config.ts
- tasks/deployEmissionsController.ts
- tasks/deployFeeders.ts
- tasks/deployIntegration.ts
- tasks/deployRevenueForwarder.ts
- tasks/deployRewards.ts
- tasks/feeder.ts
- tasks/token.ts
- tasks/utils/emissions-utils.ts
- tasks/utils/networkAddressFactory.ts
- tasks/utils/tokens.ts
- tasks/weekly.ts
- test/buy-and-make/revenue-buy-back.spec.ts
- test/emissions/emission-controller-polygon.spec.ts
- test/emissions/emission-controller.spec.ts
* Basic RevenueBuyBack unit tests
* Hardhat tasks to deploy mainnet and Polygon contracts for the Emissions Controller
* Added `getDialRecipient` to the `EmissionsController`
* Renamed `EmissionsController.CHILD_RECIPIENT` to `EmissionsController.BRIDGE_RECIPIENT`
* Removed transfer of MTA into the EmissionsController from the `initialize` function. 6 weeks worth of MTA will be pushed from a Gnosis Safe instead.
> RevenueBuyBack tests and Deployment tasks

- contracts/emissions/EmissionsController.sol
- tasks/feeder.ts
- tasks/ops.ts
- test/emissions/emission-controller.spec.ts
- Change consturctor, as now the it is required to  numbers of 9 digits on the configuration to avoid loosing precision.
From `A = _config.A * 1e12;`  to `A = _config.A * 1e3;`
- Fix overflow execption while calculating epochDelta 
```
// Uncaught Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
uint128 epochDelta = (epoch - epochs.startEpoch) * 1e18; 
```
> test: adds tests to EmissionsController.topLineEmission function (9702)

- contracts/buy-and-make/RevenueBuyBack.sol
- contracts/buy-and-make/RevenueForwarder.sol
- contracts/emissions/BasicRewardsForwarder.sol
- contracts/emissions/EmissionsController.sol
- contracts/rewards/InitializableRewardsDistributionRecipient.sol
- test/buy-and-make/revenue-buy-back.spec.ts
- test/buy-and-make/revenue-forwarder.spec.ts
- test/emissions/basic-rewards-forwarder.spec.ts
- test/emissions/emission-controller.spec.ts
* Made `RevenueForwarder` more generic with `mAsset` rather than `musd`
* `RevenueForwarder.setConfig` now emits 
* `EmissionsController` lint and Natspec tidy
* `RevenueForwarder` unit tests
* `BasicRewardsForwarder` unit tests
* More unit tests for `EmissionsController.setVoterDialWeights`
* Improved unit test coverage of `RevenueBuyBack`
> Emissions tests

- test/emissions/emission-controller.spec.ts
- Adds tests for emissions controller, calculate rewards when dials are enabled , disabled 
- Adds tests for emissions controller, after a new dial was added that was not in previous distributions
> test: adds test for emission controller when dials are disabled

- tasks/deployEmissionsController.ts
- tasks/utils/emissions-utils.ts
- tasks/utils/networkAddressFactory.ts
- test-fork/emissions/emissions-mainnet-deployment.spec.ts
This includes:
* Visor Finance basic rewards forwarder
* The three Polygon bridge forwarders for
- mUSD Vault
- FRAX Farm
- Balancer Pool 
* Treasury DAO
> Added all go-live dials to Emissions Controller fork tests

- contracts/emissions/EmissionsController.sol
- hardhat.config.ts
* using a `uint256` for the `dialWeights` in the `VoterPreferences` struct and bit operations to turn it into an array of 16 `Preference` items.
Gas from `./test/emissions/emission-controller.spec.ts ` test before change
```
|  Contract             ·  Method               ·  Min        ·  Max        ·  Avg        ·  # calls      ·  usd (avg)  │
························|·······················|·············|·············|·············|···············|··············
|  EmissionsController  ·  addDial              ·     140684  ·     180555  ·     150511  ·           36  ·          -  │
························|·······················|·············|·············|·············|···············|··············
|  EmissionsController  ·  addStakingContract   ·          -  ·          -  · …
```
> Gas optimisation for Emissions Controller

- tasks/deployFeeders.ts
- tasks/deployRewards.ts
- tasks/utils/feederUtils.ts
added the boostCoeff for the deployVault hh task as on optional param, default to 9 as per Staking V2 update.
> chore: add boostCoeff to hh task params

- tasks-fork.config.ts
- tasks.config.ts
- tasks/feeder.ts
- tasks/ironBankMigration.ts
- tasks/ops.ts
- tasks/rewards.ts
- tasks/stakingV2.ts
- tasks/utils/quest-utils.ts
- tasks/utils/snap-utils.ts
- test-fork/feeders/feeders-dudintegration.spec.ts
- test-fork/savings/liquidator.spec.ts
Changed Hardhat tasks
* `rewards` now includes min AAVE/GUSD and AAVE/WBTC rates
* `rewards` fixed so it can handle zero COMP accrued
* `staked-snap` now has optional block argument to get historical data
* `staked-snap` now reports earned MTA
* `deploy-dud-contracts` for migration of mUSD from Iron Bank for BUSD and GUSD Feeder Pools
* `quest-complete-queue` can now run again different quests. eg the new Metanaut Space Program
* `feeder-mint` can now do a single mint or multi mint
Extra fork tests
* Liquidating `stkAAVE` from BUSD and RAI Feeder Pools
* Migrating `mUSD` from Iron Bank for the BUSD and GUSD Feeder Pools
> Upgrades to Hardhat tasks

- tasks/masset.ts
Used for redeeming USDC, USDT, WBTC or renBTC
> `masset-redeem` can redeem 6 and 8 decimal bAssets

- tasks/emissions.ts
- test/emissions/votium-bribe-forwarder.spec.ts
Adds new task to forward bribes on votium. 
Run as follows :
For example on the URL  https://vote.convexfinance.com/#/proposal/QmZpsJAvbKEY9YKFCZBUzzSMC5Y9vfy6QPA4HoXGsiLUyg
the proposal is `QmZpsJAvbKEY9YKFCZBUzzSMC5Y9vfy6QPA4HoXGsiLUyg`
```
yarn task:fork votium-forward  --proposal  "QmZpsJAvbKEY9YKFCZBUzzSMC5Y9vfy6QPA4HoXGsiLUyg"
```
> chore: adds task votium-forward

- .solcover.js
- contracts/masset/liquidator/Unliquidator.sol
- tasks/deployIntegration.ts
- tasks/utils/networkAddressFactory.ts
- test-fork/savings/unliquidator.spec.ts
Contract `Unliquidator.sol` for MIP 26. To stop liquidating stkAave and COMP and transfer to a set address (in this case Asset Management SubDao).
Done fork tests in `unliquidator.spec.ts` on Ethereum mainnet.
> feat: unliquidator

- tasks/ops.ts
- tasks/rewards.ts
* Removed Hardhat tasks that claim then liquidate COMP and stkAAVE: `liq-claim-comp`, `liq-claim-aave`, `liq-trig` and `liq-trig-aave`
* Added Hardhat task `claim-comp` that claims COMP for treasury
* Added Hardhat task `claim-aave` that claims stkAAVE for treasury
* Polygon no longer needs to claim WMATIC rewards from Aave in Hardhat task `polly-daily`
> Claiming COMP and stkAAVE for treasury

- contracts/interfaces/ISavingsContract.sol
- contracts/legacy-upgraded/imbtc-mainnet-22.sol
- contracts/legacy-upgraded/imusd-mainnet-21.sol
- contracts/legacy-upgraded/imusd-mainnet-22.sol
- contracts/legacy-upgraded/imusd-polygon-22.sol
- contracts/rewards/boosted-staking/BoostedDualVault.sol
- contracts/rewards/boosted-staking/BoostedVault.sol
- contracts/rewards/staking/StakingRewards.sol
- contracts/rewards/staking/StakingRewardsWithPlatformToken.sol
- contracts/savings/SavingsContract.sol
- contracts/savings/peripheral/SaveWrapper.sol
- contracts/savings/peripheral/Unwrapper.sol
- tasks/deploySavingsContract4626.ts
- test-fork/savings/sc22-mainnet-upgrade.spec.ts
- test-fork/savings/sc22-polygon-upgrade.spec.ts
- test-utils/fork.ts
- test/savings/savings-contract.spec.ts
- test/shared/ERC4626.behaviour.ts
Amends the following peer review comments: 
- Emits double emit  events (old, new)  to keep compatibility. 
- Adds emit function with referral .
- Changes 2**256 - 1 in the imUSD contract that still uses Solidity 0.5.16. for a constant.
> test: finish fork tests for IERC4626Vault

- contracts/buy-and-make/RevenueBuyBack.sol
- contracts/buy-and-make/RevenueSplitBuyBack.sol
- contracts/z_mocks/nexus/MockNexus.sol
- tasks/deployEmissionsController.ts
- tasks/utils/emissions-utils.ts
- tasks/utils/networkAddressFactory.ts
- test-fork/buy-and-make/revenue-split.spec.ts
- test/buy-and-make/revenue-buy-back.spec.ts
- test/buy-and-make/revenue-split-buy-back.spec.ts
Forked `RevenueBuyBack` contract to `RevenueSplitBuyBack` that sends a portion of the mAssets revenue to treasury and the rest through a buy-back of reward tokens. The buy-back does a mAsset redeem to a bAsset and then a Uniswap V3 swap to the rewards token, eg MTA.
The buy-back moves the min amounts to parameters of the `buyBackRewards` function instead of being stored in contract storage. This is to better protect against sandwich attacks. Only the keeper or governor can now execute the `buyBackRewards` function as setting the min amounts needs to come from a trusted account.
Change details
* `buyBackRewards` has an array of `minBassetsAmounts`, `minRewardsAmounts` and `uniswapPaths` added as arguments to the existing array of `mAssets` argument.
* The portion of the revenue sent to the …
> Feature share revenue

- contracts/legacy-upgraded/imbtc-mainnet-22.sol
- contracts/legacy-upgraded/imusd-mainnet-22.sol
- contracts/legacy-upgraded/imusd-polygon-22.sol
- contracts/savings/SavingsContract.sol
- `maxWithdraw` and `maxRedeem` param was changed from `caller` to `owner` in the final spec. I updated `imbtc-mainnet-22`, `imusd-mainnet-22`, `imusd-polygon-22` and `SavingsContract`. 
- Completed Natspec for some of the new ERC-4626 functions.
> maxWithdraw and maxRedeem param name changes

- .eslintrc.js
- contracts/governance/staking/StakedTokenBatcher.sol
- tasks/bridge.ts
- tasks/deployRewards.ts
- tasks/stakingV2.ts
- tasks/utils/networkAddressFactory.ts
- test/governance/staking/staked-token-batcher.spec.ts
Closes https://github.com/mstable/mstable-v1-backlog/issues/5
adds new task  **staked-time-all-users**, it does the following: 
- Get all the stakers accounts for both  MTA and mBPT vaults.
- Filter all accounts where the time multiplier does not need to be updated. 
- Invokes for each account `GamifiedToken.reviewTimestamp`  to update the time multiplier.
> feat: adds new task  staked-time-all-users

- .github/ISSUE_TEMPLATE/deployment_task.md
Removed some items that are part of the notion protocol rollout plan. This list should focus more on the deployment pre and post tasks.
> chore: removed items covered in Notion

- contracts/emissions/BalRewardsForwarder.sol
- contracts/emissions/BasicRewardsForwarder.sol
- contracts/peripheral/Balancer/IChildChainStreamer.sol
- contracts/z_mocks/emissions/MockChildChainStreamer.sol
- tasks/deployEmissionsController.ts
- tasks/rewards.ts
- tasks/utils/emissions-utils.ts
- tasks/utils/networkAddressFactory.ts
- tasks/utils/tokens.ts
- test-fork/emissions/emissions-mainnet-deployment.spec.ts
- test-fork/emissions/emissions-polygon-deployment.spec.ts
- test/emissions/bal-rewards-forwarder.spec.ts
Integrate MTA Emissions to Balancer's new gauges
Updated with commit https://github.com/mstable/mStable-process-docs/commit/3538e7560a49bcc1f402f821958f136d3a3bf265
Update with commit https://github.com/mstable/mStable-defender/pull/12 
closes https://github.com/mstable/mstable-v1-backlog/issues/44
> feat: adds BalRewardsForwarder
